---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  A basic CloudFormation template for an RDS Aurora cluster.
Parameters:
  DatabaseUsername:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 1 to 16 alphanumeric characters.
    Description: The database admin account user name, between 1 to 16 alphanumeric characters.
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DatabasePassword:
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must be between 8 to 41 alphanumeric characters.
    Description: The database admin account password, between 8 to 41 alphanumeric characters.
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DatabaseName:
    AllowedPattern: "[a-zA-Z0-9-_]+"
    ConstraintDescription: must be between 4 to 30 alphanumeric characters.
    Description: The database admin account user name, between 4 to 30 alphanumeric characters.
    MaxLength: '30'
    MinLength: '4'
    Type: String
  Subnets:
    Type: "List<AWS::EC2::Subnet::Id>"  
  InstanceType: 
    Type: String
    Default: db.t2.small
    Description: Enter db Instance types.
  DBClusterIdentifier: 
    Type: String
    Description: Tenant Name  
  DBSecurityGroup:  
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group Name
  
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Database Configuration
        Parameters:
          - DatabaseName
          - DatabaseUsername
          - DatabasePassword
          - Subnets
    ParameterLabels:
      DatabaseName:
        default: Database Name
      DatabaseUsername:
        default: Database Username
      DatabasePassword:
        default: Database Password
      Subnets:
        default: DB Private Sub Nets
      InstanceType:
        default: DB Instance Type
      DBClusterIdentifier:
        default: DB Cluster Name
      DBSecurityGroup:  
        default: DB Security Group Name
        
Resources:
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudFormation managed DB subnet group.
      SubnetIds: !Ref Subnets
      
  AutoScalerTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 8
      ResourceId: !Sub "cluster:${DatabaseCluster}"
      ScalableDimension: rds:cluster:ReadReplicaCount
      ServiceNamespace: rds
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/rds.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_RDSCluster"

  AutoScaler:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      ScalingTargetId: !Ref "AutoScalerTarget"
      ServiceNamespace: rds
      PolicyName: dbib
      PolicyType: TargetTrackingScaling
      ScalableDimension: rds:cluster:ReadReplicaCount
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: RDSReaderAverageCPUUtilization
        TargetValue: 80.0
        ScaleOutCooldown: 300
        ScaleInCooldown: 300
        DisableScaleIn: False    

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      DatabaseName: !Ref "DatabaseName"
      MasterUsername: !Ref "DatabaseUsername"
      MasterUserPassword: !Ref "DatabasePassword"
      BackupRetentionPeriod: 7
      StorageEncrypted: True
      PreferredBackupWindow: 01:00-02:00
      PreferredMaintenanceWindow: mon:03:00-mon:04:00
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
      DBClusterIdentifier: !Ref "DBClusterIdentifier"
      VpcSecurityGroupIds: !Ref "DBSecurityGroup"
      Tags: 
         - 
            Key: "Name"
            Value: !Ref "DBClusterIdentifier"
            
  DatabasePrimaryInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora
      DBClusterIdentifier: !Ref "DatabaseCluster"
      DBInstanceClass: !Ref "InstanceType"
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
      Tags: 
         - 
            Key: "Name"
            Value: !Ref "DBClusterIdentifier"
  
  DatabaseReplicaInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora
      DBClusterIdentifier: !Ref "DatabaseCluster"
      DBInstanceClass: !Ref "InstanceType"
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
      Tags: 
         - 
            Key: "Name"
            Value: !Ref "DBClusterIdentifier"
